version: '3.8'

services:
  server:
    build:
      context: url-shortener-server
      dockerfile: url-shortener-server/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - CASSANDRA_HOST=cassandra
      - REDIS_HOST=redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"