version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - CASSANDRA_HOST=cassandra
      - REDIS_HOST=redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"