spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  profiles:
    active: @spring.profiles.active@

server:
  port: 8080

hostname-protocol: ${HOSTNAME_PROTOCOL:http://}
hostname: ${HOSTNAME:localhost}

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health


